'use strict';
const $=s=>document.querySelector(s);
const identity=()=>({a:1,b:1,h:0,k:0});
const state={mode:'learn',lesson:0,revealed:false,point:3,family:'shape',t:identity(),showOriginal:true,round:null,filter:'mixed'};
const points=[[-4,1],[-2,3],[0,-1],[2,2],[4,1]];
const fmt=n=>Number.isInteger(n)?String(n).replace('-','−'):String(Math.round(n*100)/100).replace('-','−');
const coord=p=>`(${fmt(p[0])}, ${fmt(p[1])})`;
const move=(p,t)=>[p[0]/t.b+t.h,t.a*p[1]+t.k];
function term(n){return n===0?'':n<0?` − ${fmt(-n)}`:` + ${fmt(n)}`;}
function coefficient(n){return n===1?'':n===-1?'−':fmt(n);}
function eq(t,colored=false){let inside=t.h?`(x${term(-t.h)})`:'x';inside=coefficient(t.b)+inside;if(t.b===1&&t.h)inside=`x${term(-t.h)}`;const out=coefficient(t.a),end=term(t.k);return colored?`g(x) = <span class="output">${out}</span>f(<span class="input">${inside}</span>)<span class="output">${end}</span>`:`g(x) = ${out}f(${inside})${end}`;}
const lessons=[
{title:'Shift up or down',short:'Vertical shifts',kind:'output',tag:'Outside · output',t:{a:1,b:1,h:0,k:3},prompt:'The equation adds 3 outside f. Which coordinate changes?',idea:'Keep each input. Add 3 to every output.',why:'At x = 2, the original output is 2. The new output is f(2) + 3 = 2 + 3 = 5.',rule:'(x, y) → (x, y + 3)',check:'If the equation were f(x) − 3, what would change?',answer:'Every point would move down 3 units. Its x-coordinate would stay the same.'},
{title:'Shift left or right',short:'Horizontal shifts',kind:'input',tag:'Inside · input',t:{a:1,b:1,h:-3,k:0},prompt:'The equation adds 3 inside f. Predict: left or right?',idea:'Find the new input that reaches the same old input.',why:'To reach the old input 2, solve x + 3 = 2. The new input is −1, so (2, 2) moves to (−1, 2). That is 3 units left.',rule:'(x, y) → (x − 3, y)',check:'Why does f(x − 3) shift right instead?',answer:'To reach the old input 2, solve x − 3 = 2. You need x = 5, so the point moves 3 units right.'},
{title:'Reflect over the x-axis',short:'Vertical reflection',kind:'output',tag:'Outside · output',t:{a:-1,b:1,h:0,k:0},prompt:'The negative sign is outside f. What happens to a point above the x-axis?',idea:'Keep the input. Reverse the sign of the output.',why:'The point (2, 2) becomes (2, −2). Positive outputs become negative; negative outputs become positive. Points on the x-axis stay fixed.',rule:'(x, y) → (x, −y)',check:'Is −f(x) the same as shifting down 1?',answer:'No. A reflection changes the sign of every output. A shift subtracts the same amount from every output.'},
{title:'Reflect over the y-axis',short:'Horizontal reflection',kind:'input',tag:'Inside · input',t:{a:1,b:-1,h:0,k:0},prompt:'The negative sign is inside f. Which coordinate changes sign?',idea:'Reverse the sign of the input. Keep the output.',why:'To reach the old input 2, solve −x = 2. The new input is −2, so (2, 2) moves to (−2, 2).',rule:'(x, y) → (−x, y)',check:'Why use an asymmetric graph for this example?',answer:'A graph symmetric about the y-axis can look unchanged after this reflection. The asymmetric graph makes the movement visible.'},
{title:'Stretch or compress vertically',short:'Vertical scale',kind:'output',tag:'Outside · output',t:{a:2,b:1,h:0,k:0},prompt:'The 2 multiplies the output. Does the point’s height double or halve?',idea:'Multiply every y-coordinate by 2.',why:'The point (2, 2) becomes (2, 4). Distances from the x-axis double. A multiplier of 0.5 would halve those distances instead.',rule:'(x, y) → (x, 2y)',check:'What does −2f(x) do?',answer:'It multiplies outputs by −2: a vertical stretch by factor 2 and a reflection over the x-axis. The negative sign controls reflection; the magnitude controls scale.'},
{title:'Stretch or compress horizontally',short:'Horizontal scale',kind:'input',tag:'Inside · input',t:{a:1,b:2,h:0,k:0},prompt:'The 2 multiplies the input inside f. Does the graph become wider or narrower?',idea:'Divide every x-coordinate by 2.',why:'To reach the old input 2, solve 2x = 2. The new input is 1. The point (2, 2) moves to (1, 2), halfway toward the y-axis.',rule:'(x, y) → (x ÷ 2, y)',check:'What does f(0.5x) do?',answer:'Solve 0.5x = old input. New x is twice the old input, so the graph stretches horizontally by factor 2.'},
{title:'Put the changes together',short:'Combine transformations',kind:'output',tag:'Inside & outside',t:{a:-2,b:1,h:-1,k:1},prompt:'Track (2, 2). Where will it land after all three changes?',idea:'Solve for the input. Then transform the output.',why:'Inside: x + 1 = 2 gives x = 1. Outside: −2(2) + 1 = −3. So (2, 2) becomes (1, −3). Reflect and scale vertically before shifting up.',rule:'(x, y) → (x − 1, −2y + 1)',check:'Why is the vertical shift last?',answer:'The output rule is −2y + 1. Shifting first would give −2(y + 1) = −2y − 2, which is a different result.'}
];
const families={shape:{name:'Asymmetric graph',formula:'A connected set of line segments',points},quadratic:{name:'Quadratic · x²',formula:'f(x) = x²',fn:x=>x*x,points:[[-2,4],[-1,1],[0,0],[1,1],[2,4]]},absolute:{name:'Absolute value · |x|',formula:'f(x) = |x|',fn:x=>Math.abs(x),points:[[-4,4],[-2,2],[0,0],[2,2],[4,4]]},sqrt:{name:'Square root · √x',formula:'f(x) = √x',fn:x=>x>=0?Math.sqrt(x):NaN,points:[[0,0],[1,1],[4,2],[9,3],[16,4]]}};
function graph(t,{show=true,family='shape',original=true,point=3,id='plot',quiz=false}={}){
 const f=families[family],p=f.points[point],q=move(p,t),range=8,s=28.5,ox=270,oy=270,X=x=>ox+x*s,Y=y=>oy-y*s;
 let svg=`<svg class="graph" viewBox="0 0 540 540" role="img" aria-labelledby="${id}-title ${id}-desc"><title id="${id}-title">${show?'Original and transformed function':'Original function: predict the transformation'}</title><desc id="${id}-desc">Window: x and y from negative 8 to positive 8. ${f.formula}. Original point ${coord(p)}.${show?` ${quiz?'Transformed key points: '+f.points.map(v=>coord(move(v,t))).join('; '):eq(t)}. Transformed point ${coord(q)}.`:' The transformed graph is hidden.'} Exact key points are available in the point table.</desc><defs><clipPath id="${id}-clip"><rect x="42" y="42" width="456" height="456"/></clipPath><marker id="${id}-arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse"><path d="M 0 0 L 10 5 L 0 10 z" fill="#ac1833"/></marker></defs>`;
 for(let i=-8;i<=8;i++){svg+=`<path d="M ${X(i)} 42 V 498 M 42 ${Y(i)} H 498" stroke="${i===0?'#85909d':'#e7eaee'}" stroke-width="${i===0?1.5:1}"/>`;if(i!==0&&i%2===0)svg+=`<text x="${X(i)}" y="${oy+20}" text-anchor="middle" fill="#616b77" font-size="13">${fmt(i)}</text><text x="${ox-10}" y="${Y(i)+4}" text-anchor="end" fill="#616b77" font-size="13">${fmt(i)}</text>`;}
 svg+=`<text x="${ox-12}" y="${oy+19}" fill="#616b77" font-size="13">0</text><text x="516" y="${oy+5}" font-size="17" fill="#20242c" font-style="italic">x</text><text x="${ox-5}" y="27" font-size="17" fill="#20242c" font-style="italic">y</text><g clip-path="url(#${id}-clip)">`;
 function path(tr){if(family==='shape')return points.map((v,i)=>(i?'L':'M')+move(v,tr).map((n,j)=>(j?Y(n):X(n)).toFixed(2)).join(' ')).join(' ');let d='',pen=false;for(let j=0;j<=1000;j++){let x=-8+j*16/1000,y=tr.a*f.fn(tr.b*(x-tr.h))+tr.k;if(!Number.isFinite(y)){pen=false;continue;}d+=(pen?'L':'M')+X(x).toFixed(2)+' '+Y(y).toFixed(2)+' ';pen=true;}return d;}
 if(original)svg+=`<path d="${path(identity())}" fill="none" stroke="#667281" stroke-width="3" stroke-dasharray="7 6" stroke-linejoin="round"/>`;
 if(show)svg+=`<path d="${path(t)}" fill="none" stroke="#ac1833" stroke-width="3.5" stroke-linejoin="round"/>`;
 if(show&&original&&Math.hypot(p[0]-q[0],p[1]-q[1])>.1)svg+=`<path d="M ${X(p[0])} ${Y(p[1])} L ${X(q[0])} ${Y(q[1])}" stroke="#ac1833" stroke-width="1.6" stroke-dasharray="3 4" marker-end="url(#${id}-arrow)"/>`;
 if(original)for(let i=0;i<f.points.length;i++){let v=f.points[i];svg+=`<circle cx="${X(v[0])}" cy="${Y(v[1])}" r="${i===point?6:3.5}" fill="white" stroke="#667281" stroke-width="2"/>`;}
 if(show)for(let i=0;i<f.points.length;i++){const v=move(f.points[i],t),x=X(v[0]),y=Y(v[1]),r=i===point?7:4;svg+=`<path d="M ${x} ${y-r} L ${x+r} ${y} L ${x} ${y+r} L ${x-r} ${y} Z" fill="#ac1833" stroke="white" stroke-width="1"/>`;}
 svg+='</g></svg>';return svg;
}
function legend(show=true,original=true){return `<div class="legend">${original?'<span><i class="swatch"></i>Original f · ○</span>':''}${show?'<span><i class="swatch new"></i>Transformed g · ◆</span>':'<span>Predict before revealing g</span>'}</div>`;}
function table(t,family,show=true){return `<table><thead><tr><th>Original (x, y)</th><th>Transformed (x, y)</th></tr></thead><tbody>${families[family].points.map(p=>`<tr><td>${coord(p)}</td><td>${show?coord(move(p,t)):'Reveal to check'}</td></tr>`).join('')}</tbody></table>`;}
function render(){document.querySelectorAll('[data-mode]').forEach(b=>{const active=b.dataset.mode===state.mode;b.classList.toggle('active',active);active?b.setAttribute('aria-current','page'):b.removeAttribute('aria-current');});if(state.mode==='learn')renderLearn();else if(state.mode==='explore')renderExplore();else renderPractice();}
function renderLearn(){const l=lessons[state.lesson];$('#main').innerHTML=`<div class="layout"><aside class="sidebar"><div class="eyebrow">The visual introduction</div><h1>Follow a point.<br>See the change.</h1><p class="intro">Predict, reveal, and explain. Move through the lesson together or at your own pace.</p><nav class="lessons" aria-label="Lesson steps">${lessons.map((x,i)=>`<button data-lesson="${i}" class="${i===state.lesson?'active':''}" ${i===state.lesson?'aria-current="step"':''}><span class="num">${i+1}</span>${x.short}</button>`).join('')}</nav><div class="anchor"><strong>Keep asking:</strong><p>Does this change the input, the output, or both?</p></div></aside><section class="work" aria-label="Current lesson"><div class="stage"><div class="stagehead"><div><div class="eyebrow">Lesson ${state.lesson+1} of ${lessons.length}</div><h2>${l.title}</h2><div class="equation">${eq(l.t,true)}</div></div><span class="tag ${l.kind}">${l.tag}</span></div><div class="stagebody"><div class="graphwrap">${graph(l.t,{show:state.revealed})}${legend(state.revealed)}</div><div class="explain"><div class="eyebrow">${state.revealed?'Make the connection':'Pause & predict'}</div><p class="prompt">${state.revealed?l.idea:l.prompt}</p>${state.revealed?`<div class="callout ${l.kind==='input'?'blue':'red'}"><p>${l.why}</p></div><div class="math">${l.rule}</div><div class="pointmap">○ (2, 2) → ◆ ${coord(move(points[3],l.t))}</div><button class="reveal" id="hide">Hide transformation</button>`:`<div class="callout"><div class="eyebrow">Track this point</div><div class="math">○ (2, 2) → ◆ (?, ?)</div></div><p class="small">Say where the point will move before checking.</p><button class="primary reveal" id="reveal">Reveal the transformation</button>`}</div></div><div class="stagefoot"><p>One change at a time. Every point follows the same rule.</p><div class="actions"><button id="prev" ${state.lesson===0?'disabled':''}>← Back</button><button id="next">${state.lesson===lessons.length-1?'Try the lab →':'Next →'}</button></div></div></div><div class="under"><details><summary>Key-point table</summary>${table(l.t,'shape',state.revealed)}</details><details><summary>One more question</summary><p>${l.check}</p><details><summary>Check the explanation</summary><p>${l.answer}</p></details></details></div></section></div>`;}
function scaleOptions(selected){return [-3,-2,-1,-.5,.5,1,2,3].map(v=>`<option value="${v}" ${v===selected?'selected':''}>${fmt(v)}</option>`).join('');}
function renderExplore(){const t=state.t;$('#main').innerHTML=`<div class="layout"><aside class="sidebar"><div class="eyebrow">Change it. Explain it.</div><h1>Explore the rule.</h1><p class="intro">Start with one control. Watch the equation and the same point together.</p><div class="controls"><div class="control"><label for="family">Original function</label><select id="family">${Object.entries(families).map(([id,f])=>`<option value="${id}" ${id===state.family?'selected':''}>${f.name}</option>`).join('')}</select></div><div class="control"><div class="rangetop"><label for="h">Horizontal shift · h</label><output id="hval">${fmt(t.h)}</output></div><input id="h" data-param="h" type="range" min="-4" max="4" step="1" value="${t.h}"><div class="limits"><span>−4 · left</span><span>right · 4</span></div></div><div class="control"><div class="rangetop"><label for="k">Vertical shift · k</label><output id="kval">${fmt(t.k)}</output></div><input id="k" data-param="k" type="range" min="-4" max="4" step="1" value="${t.k}"><div class="limits"><span>−4 · down</span><span>up · 4</span></div></div><div class="control"><label for="a">Output multiplier · a</label><select id="a" data-param="a">${scaleOptions(t.a)}</select></div><div class="control"><label for="b">Input multiplier · b</label><select id="b" data-param="b">${scaleOptions(t.b)}</select></div><label class="check"><input type="checkbox" id="original" ${state.showOriginal?'checked':''}>Show original graph</label><button class="reset" id="reset">Reset transformations</button></div></aside><section class="work"><div id="explorestage"></div><div class="under"><details><summary>Track all the key points</summary><div id="exploretable"></div></details><details><summary>How to read combined changes</summary><p>For g(x) = a f(b(x − h)) + k, match an old input u by solving b(x − h) = u. That gives x = u/b + h. The new output is ay + k.</p><p>For the horizontal coordinates, divide by b before adding h. For the vertical coordinates, multiply by a before adding k.</p><p>Factor first: f(2x − 4) = f(2(x − 2)). Here b = 2 and h = 2, so the horizontal shift is right 2.</p></details></div></section></div>`;updateExplore();}
function describe(t){const list=[];if(t.b<0)list.push('Reflect over y-axis');if(Math.abs(t.b)!==1)list.push(`Horizontal ${Math.abs(t.b)>1?'compression':'stretch'} × ${fmt(1/Math.abs(t.b))}`);if(t.h)list.push(`${t.h>0?'Right':'Left'} ${fmt(Math.abs(t.h))}`);if(t.a<0)list.push('Reflect over x-axis');if(Math.abs(t.a)!==1)list.push(`Vertical ${Math.abs(t.a)>1?'stretch':'compression'} × ${fmt(Math.abs(t.a))}`);if(t.k)list.push(`${t.k>0?'Up':'Down'} ${fmt(Math.abs(t.k))}`);return list.length?list:['No change: g(x) = f(x)'];}
function updateExplore(){const t=state.t,p=families[state.family].points[state.point],q=move(p,t),off=Math.abs(q[0])>8||Math.abs(q[1])>8;$('#hval').textContent=fmt(t.h);$('#kval').textContent=fmt(t.k);$('#explorestage').innerHTML=`<div class="stage"><div class="stagehead"><div><div class="eyebrow">${families[state.family].formula}</div><div class="equation">${eq(t,true)}</div></div><span class="tag">Live graph</span></div><div class="stagebody"><div class="graphwrap">${graph(t,{family:state.family,original:state.showOriginal,point:state.point})}${legend(true,state.showOriginal)}</div><div class="explain"><div class="eyebrow">One rule for every point</div><div class="math">g(x) = a f(b(x − h)) + k</div><div class="callout blue"><div class="eyebrow">New horizontal coordinate</div><div class="math">x<sub>new</sub> = x<sub>old</sub> ÷ b + h</div></div><div class="callout red"><div class="eyebrow">New vertical coordinate</div><div class="math">y<sub>new</sub> = a · y<sub>old</sub> + k</div></div><div class="control"><label for="point">Follow an original point</label><select id="point">${families[state.family].points.map((v,i)=>`<option value="${i}" ${i===state.point?'selected':''}>${coord(v)}</option>`).join('')}</select></div><div class="pointmap">○ ${coord(p)} → ◆ ${coord(q)}</div><p class="small">${off?'The transformed point is outside the displayed window. Its exact coordinates are shown above.':'Circles mark original points; diamonds mark transformed points.'}</p></div></div><div class="stagefoot"><div class="chips">${describe(t).map(v=>`<span>${v}</span>`).join('')}</div></div></div>`;$('#exploretable').innerHTML=table(t,state.family);}
const bank=[];
function addQ(type,prompt,expression,correct,wrong,explanation,t=null){bank.push({id:bank.length,type,prompt,expression,correct,options:[correct,...wrong],explanation,t});}
for(const n of [2,3,4]){
 addQ('identify','Describe the change to the graph of f.',`g(x) = f(x) + ${n}`,`Shift up ${n}`, [`Shift down ${n}`,`Shift right ${n}`,`Shift left ${n}`],`The ${n} is added outside f, so add ${n} to each y-coordinate.`);
 addQ('identify','Describe the change to the graph of f.',`g(x) = f(x + ${n})`,`Shift left ${n}`,[`Shift right ${n}`,`Shift up ${n}`,`Shift down ${n}`],`Solve x + ${n} = old input. The new x-coordinate is ${n} less.`);
 addQ('identify','Describe the change to the graph of f.',`g(x) = f(x − ${n})`,`Shift right ${n}`,[`Shift left ${n}`,`Shift down ${n}`,`Shift up ${n}`],`Solve x − ${n} = old input. The new x-coordinate is ${n} greater.`);
 addQ('equation',`Which equation shifts the graph down ${n} units?`,'',`g(x) = f(x) − ${n}`,[`g(x) = f(x − ${n})`,`g(x) = f(x + ${n})`,`g(x) = f(x) + ${n}`],`A downward shift subtracts ${n} from the output, outside the function.`);
}
addQ('identify','Which axis is the graph reflected over?','g(x) = −f(x)','The x-axis',['The y-axis','Both axes','Neither axis'], 'The outside negative changes y to −y. The x-coordinate stays the same.');
addQ('identify','Which axis is the graph reflected over?','g(x) = f(−x)','The y-axis',['The x-axis','Both axes','Neither axis'], 'Solve −x = old input: the horizontal coordinate changes sign.');
addQ('identify','Which scale change is described?','g(x) = 2f(x)','Vertical stretch by factor 2',['Horizontal stretch by factor 2','Vertical compression by factor 0.5','Horizontal compression by factor 0.5'],'The output is multiplied by 2; every y-coordinate doubles.');
addQ('identify','Which scale change is described?','g(x) = f(2x)','Horizontal compression by factor 0.5',['Horizontal stretch by factor 2','Vertical stretch by factor 2','Vertical compression by factor 0.5'],'Solve 2x = old input. Every x-coordinate is divided by 2.');
addQ('identify','Which scale change is described?','g(x) = f(0.5x)','Horizontal stretch by factor 2',['Horizontal compression by factor 0.5','Vertical stretch by factor 2','Vertical compression by factor 0.5'],'Solve 0.5x = old input. Every x-coordinate doubles.');
addQ('identify','Which scale change is described?','g(x) = 0.5f(x)','Vertical compression by factor 0.5',['Horizontal compression by factor 0.5','Vertical stretch by factor 2','Horizontal stretch by factor 2'],'The multiplier is outside f. Multiply each output by 0.5.');
addQ('equation','Choose the rule: reflect over the y-axis, then shift up 2.','','g(x) = f(−x) + 2',['g(x) = −f(x) + 2','g(x) = f(−x + 2)','g(x) = f(x − 2)'],'The reflection changes the input to −x. The upward shift adds 2 to the output.');
addQ('equation','Choose the rule: stretch vertically by 3, then shift down 1.','','g(x) = 3f(x) − 1',['g(x) = f(3x) − 1','g(x) = 3f(x − 1)','g(x) = 3(f(x) − 1)'],'Multiply the original output by 3, then subtract 1. Shifting before scaling would give 3f(x) − 3.');
addQ('equation','Choose the rule: shift right 2 and reflect over the x-axis.','','g(x) = −f(x − 2)',['g(x) = f(−x − 2)','g(x) = −f(x + 2)','g(x) = f(x − 2) − 1'],'A right shift uses x − 2 inside f. Reflection over the x-axis negates the output.');
addQ('equation','Which rule stretches the graph horizontally by factor 2?','','g(x) = f(x/2)',['g(x) = f(2x)','g(x) = 2f(x)','g(x) = f(x) + 2'],'The inside multiplier is 0.5. New x = old x ÷ 0.5 = 2 times old x.');
const pointCases=[{t:{a:1,b:1,h:-3,k:0},p:[2,4],wrong:[[5,4],[2,7],[2,1]]},{t:{a:-1,b:1,h:2,k:0},p:[1,3],wrong:[[-1,-3],[3,3],[-3,3]]},{t:{a:2,b:1,h:0,k:1},p:[-2,3],wrong:[[-4,7],[-2,8],[-2,5]]},{t:{a:1,b:2,h:0,k:0},p:[4,3],wrong:[[8,3],[4,6],[4,1.5]]},{t:{a:1,b:-1,h:0,k:0},p:[-2,3],wrong:[[-2,-3],[2,-3],[-3,2]]},{t:{a:1,b:.5,h:0,k:0},p:[2,3],wrong:[[1,3],[2,6],[2,1.5]]},{t:{a:-2,b:1,h:-1,k:1},p:[2,2],wrong:[[3,-3],[1,-6],[1,5]]},{t:{a:1,b:2,h:2,k:0},p:[4,3],wrong:[[6,3],[0,3],[4,6]]}];
for(const c of pointCases)addQ('point',`The point ${coord(c.p)} is on f. Which point must be on g?`,eq(c.t),coord(move(c.p,c.t)),c.wrong.map(coord),`New x = ${fmt(c.p[0])} ÷ (${fmt(c.t.b)})${term(c.t.h)} = ${fmt(move(c.p,c.t)[0])}. New y = (${fmt(c.t.a)})(${fmt(c.p[1])})${term(c.t.k)} = ${fmt(move(c.p,c.t)[1])}.`);
for(const t of [{a:1,b:1,h:2,k:0},{a:1,b:1,h:0,k:-2},{a:-1,b:1,h:0,k:0},{a:1,b:-1,h:0,k:0},{a:2,b:1,h:0,k:0},{a:1,b:2,h:0,k:0}]){
const alternatives=[{a:1,b:1,h:-2,k:0},{a:1,b:1,h:0,k:2},{a:-1,b:1,h:0,k:0},{a:1,b:-1,h:0,k:0},{a:2,b:1,h:0,k:0},{a:1,b:2,h:0,k:0}].map(x=>eq(x)).filter(x=>x!==eq(t)).slice(0,3);
addQ('graph','Which equation matches the red, solid graph?','',eq(t),alternatives,`${describe(t).join('; ')}. Follow the marked original point (2, 2): it becomes ${coord(move([2,2],t))}.`,t);}
addQ('identify','Factor the input first. What is the horizontal shift?','g(x) = f(2x − 4)','Right 2',['Right 4','Left 2','Left 4'],'2x − 4 = 2(x − 2). Divide original x-coordinates by 2, then add 2.');
const shuffle=a=>{const r=[...a];for(let i=r.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[r[i],r[j]]=[r[j],r[i]];}return r;};
function startRound(pool){let selected;if(pool)selected=shuffle(pool);else if(state.filter==='mixed'){selected=shuffle([...shuffle(bank.filter(q=>q.type==='identify')).slice(0,2),...shuffle(bank.filter(q=>q.type==='equation')).slice(0,2),...shuffle(bank.filter(q=>q.type==='point')).slice(0,2),...shuffle(bank.filter(q=>q.type==='graph')).slice(0,2)]);}else selected=shuffle(bank.filter(q=>q.type===state.filter)).slice(0,8);state.round={questions:selected.map(q=>({...q,options:shuffle(q.options)})),index:0,answers:[],selected:null};}
function renderPractice(){if(!state.round)startRound();const r=state.round,done=r.index>=r.questions.length,correct=r.answers.filter(a=>a.correct).length;$('#main').innerHTML=`<div class="practicewrap"><div class="practicehead"><div><div class="eyebrow">Retrieval practice</div><h1>Notice it. Name it.</h1><p>Short rounds. Think first, then check your reasoning.</p></div><span class="tag">No timer · No grades</span></div><div class="practicefilters"><label for="practiceType">Practice</label><select id="practiceType">${[['mixed','Mixed review'],['identify','Name the change'],['equation','Words → equation'],['point','Move a point'],['graph','Graph → equation']].map(([v,n])=>`<option value="${v}" ${state.filter===v?'selected':''}>${n}</option>`).join('')}</select><button id="newround">Start a new round</button></div><div class="roundbar"><span>${done?'Round complete':`Question ${r.index+1} of ${r.questions.length}`}</span><span>${correct} correct · ${r.answers.length} answered</span></div><div class="progress"><i style="width:${r.answers.length/r.questions.length*100}%"></i></div><section class="stage question" aria-label="Practice question">${done?renderResults():renderQuestion()}</section></div>`;}
function renderQuestion(){const r=state.round,q=r.questions[r.index],answered=r.selected!==null;return `<div class="eyebrow">${{identify:'Name the change',equation:'Words → equation',point:'Move a point',graph:'Read the graph'}[q.type]}</div><h2 id="questiontext">${q.prompt}</h2>${q.expression?`<div class="equation">${q.expression}</div>`:''}${q.t?`<div class="questiongraph">${graph(q.t,{id:'quiz',quiz:true})}${legend()}</div>`:''}<div class="answers" aria-labelledby="questiontext">${q.options.map((op,i)=>`<button class="answer ${answered&&op===q.correct?'correct':''} ${answered&&r.selected===i&&op!==q.correct?'wrong':''}" data-answer="${i}" ${answered?'disabled':''}><b>${String.fromCharCode(65+i)}</b><span>${op}${answered&&op===q.correct?' ✓':''}${answered&&r.selected===i&&op!==q.correct?' ✕':''}</span></button>`).join('')}</div>${answered?`<div class="feedback" tabindex="-1" id="feedback" role="status"><h3>${q.options[r.selected]===q.correct?'Correct.':'Let’s trace the change.'}</h3><p><strong>${q.correct}</strong></p><p>${q.explanation}</p><button class="primary" id="nextquestion">${r.index===r.questions.length-1?'See round results':'Next question →'}</button></div>`:'<p class="small">Choose one answer. You’ll see the reason before moving on.</p>'}`;}
function renderResults(){const r=state.round,missed=r.answers.filter(a=>!a.correct),correct=r.answers.length-missed.length;return `<div class="eyebrow">Round complete</div><h2>${missed.length?'Here is what to revisit.':'You connected the changes.'}</h2><div class="summaryscore">${correct}<span class="small"> / ${r.questions.length} correct</span></div><p>${missed.length?'Revisit the missed ideas, then try retrieving them again.':'Try another round or explain one of these rules aloud without looking.'}</p><div class="actions">${missed.length?'<button class="primary" id="retry">Practice missed questions</button>':''}<button id="newround">New round</button><button data-mode="learn">Back to the lesson</button></div>${missed.map(a=>`<div class="reviewitem"><strong>${a.q.prompt}</strong><div class="math">${a.q.expression}</div><p class="small">Your answer: ${a.chosen}</p><p>Correct: ${a.q.correct}</p><p class="small">${a.q.explanation}</p></div>`).join('')}`;}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b||b.disabled)return;if(b.dataset.mode){state.mode=b.dataset.mode;render();return;}if(b.dataset.lesson!==undefined){state.lesson=+b.dataset.lesson;state.revealed=false;renderLearn();return;}if(b.dataset.answer!==undefined){const r=state.round;if(r.selected!==null)return;r.selected=+b.dataset.answer;const q=r.questions[r.index];r.answers.push({q,chosen:q.options[r.selected],correct:q.options[r.selected]===q.correct});renderPractice();$('#feedback').focus({preventScroll:true});return;}switch(b.id){case'present':document.body.classList.toggle('present');b.setAttribute('aria-pressed',document.body.classList.contains('present'));b.textContent=document.body.classList.contains('present')?'Exit presentation':'Presentation view';break;case'reveal':state.revealed=true;renderLearn();$('#hide').focus({preventScroll:true});break;case'hide':state.revealed=false;renderLearn();$('#reveal').focus({preventScroll:true});break;case'prev':state.lesson--;state.revealed=false;renderLearn();break;case'next':if(state.lesson===lessons.length-1){state.mode='explore';render();}else{state.lesson++;state.revealed=false;renderLearn();}break;case'reset':state.t=identity();renderExplore();break;case'newround':startRound();renderPractice();break;case'nextquestion':state.round.index++;state.round.selected=null;renderPractice();$('#main').focus({preventScroll:true});break;case'retry':startRound(state.round.answers.filter(a=>!a.correct).map(a=>a.q));renderPractice();break;}});
document.addEventListener('input',e=>{if(e.target.matches('input[data-param]')){state.t[e.target.dataset.param]=+e.target.value;updateExplore();}});
document.addEventListener('change',e=>{const el=e.target;if(el.matches('select[data-param]')){state.t[el.dataset.param]=+el.value;updateExplore();}if(el.id==='family'){state.family=el.value;state.point=state.family==='sqrt'?2:3;updateExplore();}if(el.id==='point'){state.point=+el.value;updateExplore();$('#point').focus({preventScroll:true});}if(el.id==='original'){state.showOriginal=el.checked;updateExplore();}if(el.id==='practiceType'){state.filter=el.value;startRound();renderPractice();$('#practiceType').focus({preventScroll:true});}});
render();
